services:
  postgres:
    ports:
      - "5433:5432"
    restart: always

  backend:
    build:
      context: ./backend/reservation-calendar-be
      dockerfile: Dockerfile.dev.dockerfile
    container_name: spring-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/reservation-calendar-be:/app
      - ~/.gradle:/root/.gradle
    working_dir: /app
    depends_on:
      - postgres
    restart: always

  frontend:
    build:
      context: ./frontend/reservation-calendar-fe
      dockerfile: Dockerfile.dev.dockerfile
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/reservation-calendar-fe:/app
    working_dir: /app
    depends_on:
      - backend
    restart: always
#실행 명령어: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build -> 뒤에 오는 파일이 앞에 오는 파일을 덮어씀 (순서 중요!)
